using System.IO;
using System.Diagnostics;

namespace python_run
{
    public class NeyralStyleRunnerPython
    {
        public NeyralStyleRunnerPython()
        {


        }

        public string [] Execute(string args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "python3";
            start.WorkingDirectory = System.Environment.GetEnvironmentVariable("NEURAL_STYLE_HOME");
            start.Arguments = string.Format("\"{0}\" {1}", "neural_style.py", args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    process.WaitForExit();
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return new string [] { result, stderr };
                }
            }
        }
    }
}
